name: Deploy .NET App to EC2

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Publish .NET app
      working-directory: GuessMaster.API
      run: dotnet publish -c Release -o publish
        
  deploy:
    runs-on: self-hosted

    steps:
    - name: Move to app dir
      run: |
          cp -r GuessMaster.API/publish/* /home/ec2-user/Guess-Master-ec2/
          sudo systemctl restart myapp

