name: Deploy .NET App to EC2

on:
  push:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Apply EF Core migrations
      run: |
        export PATH="$PATH:$HOME/.dotnet/tools"
        cd GuessMaster.Data
        dotnet ef database update --startup-project ../GuessMaster.API --connection "Server=${{ secrets.SQL_SERVER }};Database=${{ secrets.SQL_DB }};User Id=${{ secrets.SQL_USER }};Password=${{ secrets.SQL_PASS }};"

    - name: Publish .NET app
      run: dotnet publish -c Release -o publish
        
    - name: Move to app dir
      run: |
        cp -r publish/* /home/ec2-user/Guess-Master-ec2/
        sudo systemctl restart myapp
    

