name: Deploy .NET App to EC2

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: amazon-linux

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Or your version

    - name: Publish .NET app
      run: dotnet publish -c Release -o publish

    - name: Copy files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        source: "publish/*"
        target: ${{ secrets.APP_DIR }}

    - name: Restart app on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
            sudo systemctl restart myapp
            sudo systemctl status myapp --no-pager

