name: Weekly SQL Cleanup on Self-Hosted Runner

on:
  push:
    branches: [ master ]  # every Monday at 03:00 UTC

jobs:
  cleanup:
    runs-on: self-hosted   # This tells GitHub Actions to use your EC2 runner

    steps:
      - name: Run cleanup query
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASS: ${{ secrets.SQL_PASS }}
          SQL_DB: gm-prod
        run: |
          /opt/mssql-tools/bin/sqlcmd -S $SQL_SERVER -U $SQL_USER -P $SQL_PASS -d $SQL_DB -Q "DELETE FROM Users WHERE UpdatedAt < DATEADD(day, -7, GETDATE());"
